### PR TITLE
[FLINK-10618] first test pr

### PR DESCRIPTION
**Pull request by flinkqa**

### CODE REVIEW

**Comment by flinkqa** [comment]
Tested pull request

**Comment by flinkqa** [comment]
Tested pull request

**Comment by flinkqa** [comment]
please run qa

**Comment by flinkqa** [comment]
Tested pull request

**Comment by flinkqa** [comment]
Tested pull request

**Comment by flinkqa** [comment]
run qa

**Comment by flinkqa** [comment]
Thanks a lot for your contribution to the Apache Flink project. I'm the @flinkqa. I help the community
to review your pull request. We will use this comment to track the progress of the review.


## Review Progress

* ✅ 1. The [description] looks good.
    - Approved by @flinkqa
* ✅ 2. There is [consensus] that the contribution should go into to Flink.
    - Approved by @rmetzger [PMC]
* ❗ 3. Needs [attention] from.
    - Needs attention by @stratosphere-javadocs
* ✅ 4. The change fits into the overall [architecture].
    - Approved by @rmetzger [PMC]
* ✅ 5. Overall code [quality] is good.
    - Approved by @rmetzger [PMC]

Please see the [Pull Request Review Guide](https://flink.apache.org/reviewing-prs.html) for a full explanation of the review process.<details>
  <summary>Bot commands</summary>
  The @flinkqa bot supports the following commands:

 - `@flinkqa approve description` to approve the 1st aspect (similarly, it also supports the `consensus`, `architecture` and `quality` keywords)
 - `@flinkqa approve all` to approve all aspects
 - `@flinkqa approve-until architecture` to approve everything until `architecture`
 - `@flinkqa attention @username1 [@username2 ..]` to require somebody's attention
 - `@flinkqa disapprove architecture` to remove an approval
</details>

**Comment by rmetzger** [comment]
This is all nice and cool. I'm trying to review the PR soon.

**Comment by rmetzger** [comment]
Okay, thanks a lot

@flinkqa contribution approved

**Comment by flinkqa** [comment]
@flinkqa approve description

**Comment by rmetzger** [comment]
@flinkqa approve description

**Comment by rmetzger** [comment]
@flinkqa approve quality

**Comment by rmetzger** [comment]
@flinkqa approve all

**Comment by rmetzger** [comment]
@flinkqa dissapprove architecture

**Comment by rmetzger** [comment]
@flinkqa disapprove description

**Comment by rmetzger** [comment]
@flinkqa adsjqi

**Comment by rmetzger** [comment]
@flinkqa approve all

**Comment by rmetzger** [comment]
@flinkqa disapprove description

**Comment by rmetzger** [comment]
I'm a reviewer now.
@flinkqa attention @stratosphere-javadocs  
is a reviewer too (hopefully)

**Pull request closed without merging**
