### PR TITLE
FLINK-13417 Create yolo.it

### PR DESCRIPTION
**Pull request by rmetzger**

### CODE REVIEW

**Comment by flinkqa** [comment]
Thanks a lot for your contribution to the Apache Flink project. I'm the @flinkqa. I help the community
to review your pull request. We will use this comment to track the progress of the review.


Last check on commit 80cf0a5c3825efefb17554e12d76e7c34d44811f (Fri Aug 02 16:15:15 CEST 2019)

**Warnings:**
 * No documentation files were touched! Remember to keep the Flink docs up to date!
 * **Invalid pull request title: No valid Jira ID provided**

## Review Progress

* ❓ 1. The [description] looks good.
* ❓ 2. There is [consensus] that the contribution should go into to Flink.
* ❓ 3. Needs [attention] from.
* ❓ 4. The change fits into the overall [architecture].
* ❓ 5. Overall code [quality] is good.

Please see the [Pull Request Review Guide](https://flink.apache.org/reviewing-prs.html) for a full explanation of the review process.<details>
 The Bot is tracking the review progress through labels. Labels are applied according to the order of the review items. For consensus, approval by a Flink committer of PMC member is required <summary>Bot commands</summary>
  The @flinkqa bot supports the following commands:

 - `@flinkqa approve description` to approve one or more aspects (aspects: `description`, `consensus`, `architecture` and `quality`)
 - `@flinkqa approve all` to approve all aspects
 - `@flinkqa approve-until architecture` to approve everything until `architecture`
 - `@flinkqa attention @username1 [@username2 ..]` to require somebody's attention
 - `@flinkqa disapprove architecture` to remove an approval you gave earlier
</details>

**Comment by flinkqa** [comment]
Thanks a lot for your contribution to the Apache Flink project. I'm the @flinkqa. I help the community
to review your pull request. We will use this comment to track the progress of the review.


## Automated ChecksLast check on commit 80cf0a5c3825efefb17554e12d76e7c34d44811f (Fri Aug 02 16:17:12 CEST 2019)

**Warnings:**
 * No documentation files were touched! Remember to keep the Flink docs up to date!
 * **Invalid pull request title: No valid Jira ID provided**

## Review Progress

* ❓ 1. The [description] looks good.
* ❓ 2. There is [consensus] that the contribution should go into to Flink.
* ❓ 3. Needs [attention] from.
* ❓ 4. The change fits into the overall [architecture].
* ❓ 5. Overall code [quality] is good.

Please see the [Pull Request Review Guide](https://flink.apache.org/reviewing-prs.html) for a full explanation of the review process.<details>
 The Bot is tracking the review progress through labels. Labels are applied according to the order of the review items. For consensus, approval by a Flink committer of PMC member is required <summary>Bot commands</summary>
  The @flinkqa bot supports the following commands:

 - `@flinkqa approve description` to approve one or more aspects (aspects: `description`, `consensus`, `architecture` and `quality`)
 - `@flinkqa approve all` to approve all aspects
 - `@flinkqa approve-until architecture` to approve everything until `architecture`
 - `@flinkqa attention @username1 [@username2 ..]` to require somebody's attention
 - `@flinkqa disapprove architecture` to remove an approval you gave earlier
</details>

**Comment by flinkqa** [comment]
Thanks a lot for your contribution to the Apache Flink project. I'm the @flinkqa. I help the community
to review your pull request. We will use this comment to track the progress of the review.


## Automated Checks
##CHECKS PLACEHOLDER##
## Review Progress

* ❓ 1. The [description] looks good.
* ❓ 2. There is [consensus] that the contribution should go into to Flink.
* ❓ 3. Needs [attention] from.
* ❓ 4. The change fits into the overall [architecture].
* ❓ 5. Overall code [quality] is good.

Please see the [Pull Request Review Guide](https://flink.apache.org/reviewing-prs.html) for a full explanation of the review process.<details>
 The Bot is tracking the review progress through labels. Labels are applied according to the order of the review items. For consensus, approval by a Flink committer of PMC member is required <summary>Bot commands</summary>
  The @flinkqa bot supports the following commands:

 - `@flinkqa approve description` to approve one or more aspects (aspects: `description`, `consensus`, `architecture` and `quality`)
 - `@flinkqa approve all` to approve all aspects
 - `@flinkqa approve-until architecture` to approve everything until `architecture`
 - `@flinkqa attention @username1 [@username2 ..]` to require somebody's attention
 - `@flinkqa disapprove architecture` to remove an approval you gave earlier
</details>

**Comment by rmetzger** [comment]
@flinkqa are you updating it. and if, how?

**Comment by rmetzger** [comment]
@flinkqa update me

**Pull request closed without merging**
